"""Create initial tables

Revision ID: 3e391a62df19
Revises: 
Create Date: 2025-05-10 18:05:08.207185

"""
from typing import Sequence, Union

import geoalchemy2
from alembic import op
import sqlalchemy as sa
from migrations.seeding_scripts import seed_db

# revision identifiers, used by Alembic.
revision: str = '3e391a62df19'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
        sa.Column('link_id', sa.Integer(), nullable=False),
        sa.Column('length', sa.Float(), nullable=True),
        sa.Column('road_name', sa.String(), nullable=True),
        sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTILINESTRING', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
        sa.Column('usdk_speed_category', sa.Integer(), nullable=True),
        sa.Column('funclass_id', sa.Integer(), nullable=True),
        sa.Column('speedcat', sa.Integer(), nullable=True),
        sa.Column('volume_value', sa.Integer(), nullable=True),
        sa.Column('volume_bin_id', sa.Integer(), nullable=True),
        sa.Column('volumes_bin_description', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('link_id')
    )
    op.create_table('speed_records',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('link_id', sa.Integer(), nullable=True),
        sa.Column('date_time', sa.DateTime(), nullable=True),
        sa.Column('freeflow', sa.Float(), nullable=True),
        sa.Column('count', sa.Integer(), nullable=True),
        sa.Column('std_dev', sa.Float(), nullable=True),
        sa.Column('min', sa.Float(), nullable=True),
        sa.Column('max', sa.Float(), nullable=True),
        sa.Column('confidence', sa.Float(), nullable=True),
        sa.Column('average_speed', sa.Float(), nullable=True),
        sa.Column('average_pct_85', sa.Float(), nullable=True),
        sa.Column('average_pct_95', sa.Float(), nullable=True),
        sa.Column('day_of_week', sa.Integer(), nullable=True),
        sa.Column('period', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['link_id'], ['links.link_id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # Read the parquet file and ingest the data
    bind = op.get_bind() # Get the current database connection. Pass it to our seeding function.
    seed_db(bind)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('speed_records')
    op.drop_table('links')
    # ### end Alembic commands ###
